spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Student_Service_Management?createDatabaseIfNotExist=true
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update